# Generated by Django 5.0.3 on 2024-03-18 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="书名")),
                (
                    "publish",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="出版社"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="作者"
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="价格")),
                (
                    "IECN",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ISBN"
                    ),
                ),
                ("notice", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
        ),
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="学院名称")),
                ("notice", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="专业名称")),
                ("notice", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.college",
                        verbose_name="所属学院",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="班级名称")),
                ("notice", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.major",
                        verbose_name="所属专业",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SemesterOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="学期名称")),
                ("notice", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.grade",
                        verbose_name="所属班级",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notice", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.books",
                        verbose_name="书籍",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.semesterorder",
                        verbose_name="学期",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="学生姓名")),
                ("notice", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="账号",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.grade",
                        verbose_name="所属班级",
                    ),
                ),
            ],
        ),
    ]
