# Generated by Django 5.0.3 on 2024-03-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="books",
            options={"verbose_name": "书籍", "verbose_name_plural": "书籍"},
        ),
        migrations.AlterModelOptions(
            name="college",
            options={"verbose_name": "学院", "verbose_name_plural": "学院"},
        ),
        migrations.AlterModelOptions(
            name="grade",
            options={"verbose_name": "班级", "verbose_name_plural": "班级"},
        ),
        migrations.AlterModelOptions(
            name="major",
            options={"verbose_name": "专业", "verbose_name_plural": "专业"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "订单", "verbose_name_plural": "订单"},
        ),
        migrations.AlterModelOptions(
            name="semesterorder",
            options={"verbose_name": "学期订单", "verbose_name_plural": "学期订单"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "学生", "verbose_name_plural": "学生"},
        ),
    ]
