# Generated by Django 5.0.3 on 2024-03-18 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_rename_iecn_books_isbn"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="反馈内容")),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="反馈时间")),
                ("msg", models.TextField(blank=True, null=True, verbose_name="回复")),
                (
                    "msg_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="回复时间"),
                ),
                (
                    "msg_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="回复账号",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.student",
                        verbose_name="学生",
                    ),
                ),
                (
                    "tabel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.semesterorder",
                        verbose_name="学期",
                    ),
                ),
            ],
            options={
                "verbose_name": "反馈",
                "verbose_name_plural": "反馈",
            },
        ),
    ]
