# Generated by Django 5.0.3 on 2024-04-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_student_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(max_length=100, verbose_name='反馈内容'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='msg',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='回复'),
        ),
    ]
