"""
Django settings for book project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lv5nug5jc!wm#vtzo7jty3*1d3bg&=*drm(zltn%#=!ug1ba7_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
    'manager',
    'user',
    'books'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'book.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'templates' / 'manager', BASE_DIR / 'templates' / 'user'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'book.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    #     'default':
    # {
    #     'ENGINE': 'django.db.backends.mysql',    # 数据库引擎
    #     'NAME': 'book', # 数据库名称
    #     'HOST': '192.168.0.108', # 数据库地址，本机 ip 地址 127.0.0.1
    #     'PORT': 3306, # 端口
    #     'USER': 'root',  # 数据库用户名
    #     'PASSWORD': '123456', # 数据库密码
    # }
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SIMPLEUI_INDEX ="http://127.0.0.1/manager/home/"
# SIMPLEUI_HOME_PAGE  ="http://127.0.0.1/manager/home/"
SIMPLEUI_HOME_INFO = False
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['学院', '书本','学期任务','反馈处理', '权限认证'],  # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    'dynamic': False,  # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [
        {
            'name': '学院',
            'icon': 'fa-solid fa-hourglass-start',
            'models': [{
                'name': '学院',
                # 注意url按'/admin/应用名小写/模型名小写/'命名。
                'url': '/admin/books/college/',
                'icon': 'fa fa-tasks'
            }, {
                'name': '专业',
                # 注意url按'/admin/应用名小写/模型名小写/'命名。
                'url': '/admin/books/major/',
                'icon': 'fa fa-tasks'
            }, {
                'name': '班级',
                # 注意url按'/admin/应用名小写/模型名小写/'命名。
                'url': '/admin/books/grade/',
                'icon': 'fa fa-tasks'
            }, {
                'name': '学生',
                # 注意url按'/admin/应用名小写/模型名小写/'命名。
                'url': '/admin/books/student/',
                'icon': 'fa fa-tasks'
            }, ]
        }, {
            'name': '书本',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '书籍管理',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/books/books/',
                    'icon': 'fa fa-tasks'
                }
            ]
        },
        {
            'name': '学期任务',
            # 注意url按'/admin/应用名小写/模型名小写/'命名。
            'url': '/admin/books/semesterorder/',
            'icon': 'fa fa-tasks'
        },{
            'name': '反馈处理',
            # 注意url按'/admin/应用名小写/模型名小写/'命名。
            'url': '/admin/books/feedback/',
            'icon': 'fa fa-tasks'
        },
        {
            'name': '权限认证',
            'icon': 'fas fa-user-shield',
            'models': [{
                'name': '用户',
                'icon': 'fa fa-user',
                'url': 'auth/user/'
            }]
        }
    ]
}
